const Arrow=()=> <svg viewBox="0 0 20 20" fill="none"><path d="M3 10h13m-5-5 5 5-5 5" stroke="currentColor" strokeWidth="1.5"/></svg>;
const services=[
 ["SVC-01","Equipment rental","Cranes, excavators and heavy machinery with logistics tracking to site.","https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85"],
 ["SVC-02","Bulk aggregates & RFQ","Request quotes on construction materials across multiple sites at once.","https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?auto=format&fit=crop&w=1200&q=85"],
 ["SVC-03","Skilled manpower","Source vetted crews for industrial and construction work.","https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85"],
 ["SVC-04","Environmental remediation","Request and track specialized ecological and site remediation services.","https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=1200&q=85"]
];
const steps=[["01","Request","Submit an RFQ or booking for one or multiple sites."],["02","Quote","Compare vendor quotes in one view."],["03","Book","Confirm and schedule delivery or service."],["04","Track","Follow status from dispatch to site."],["05","Deliver","Confirm receipt and close the order."]];
const ai=[["01","Personalization","Catalog and dashboard ranked by your site history and order patterns."],["02","Computer vision","Site and equipment photos assessed automatically for condition and progress."],["03","AI assistant","Draft an RFQ or triage an emergency ticket, instantly."],["04","Data automation","Draft quotes and status updates generated as orders move."]];
export default function Home(){return <main>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:"CED Integrated Nigeria Limited",url:"https://ced.ng",logo:"https://ced.ng/logo.png",description:"Industrial procurement, equipment rental, logistics, manpower and site support across Nigeria.",areaServed:{"@type":"Country",name:"Nigeria"},contactPoint:{"@type":"ContactPoint",email:"operations@ced.ng",contactType:"customer service"}})}}/>
 <header><a className="brand" href="#top" aria-label="CED Integrated Nigeria Limited home"><img src="/logo.png" alt=""/><span>CED <small>Integrated Nigeria Limited</small></span></a><nav aria-label="Main navigation"><a href="#services">Catalog</a><a href="#how">How it works</a><a href="#ai">AI layer</a><a href="#emergency">Emergency support</a></nav><a className="head-cta" href="/auth">Open workspace <Arrow/></a></header>
 <section className="hero" id="top"><div className="grid"/><span className="kicker"><i/> Industrial operations platform · Nigeria</span><h1>The operating system for <em>serious</em> infrastructure.</h1><p>Request equipment, aggregates and manpower, track delivery across every site, and escalate emergencies — without switching systems.</p><div className="actions"><a className="btn acid" href="/auth">Enter the platform <Arrow/></a><a href="#services" className="under">Explore the catalog ↘</a></div>
 <div className="manifest"><div className="mhead"><div><small>LIVE OPERATIONS</small><h2>Site manifest</h2></div><span><i/> Live</span></div>{[["RFQ-1042","Aggregates","Site 3 · Lekki","Reviewing"],["BK-0311","50T crane","Site 1 · Ibadan","In transit"],["ENV-0087","Remediation survey","Site 5 · Bonny","Scheduled"],["ORD-2209","Rebar 12mm","Site 3 · Lekki","Delivered"]].map((r,i)=><div className="mrow" key={r[0]}><code>{r[0]}</code><strong>{r[1]}</strong><span>{r[2]}</span><b className={`s s${i}`}>{r[3]}</b></div>)}</div></section>
 <section className="metrics"><div><strong>24<small>h</small></strong><p>Average time from RFQ<br/>to first quote</p></div><div><strong>4</strong><p>Supply categories in<br/>one catalog</p></div><div><strong>1</strong><p>Command centre for<br/>every active site</p></div></section>
 <section className="section" id="services"><div className="intro"><span className="label">01 / Capabilities</span><h2>Everything the site needs.<br/><em>One accountable partner.</em></h2><p>From the first request to final delivery, CED keeps procurement and operations in one auditable flow.</p></div><div className="cards">{services.map(s=><article key={s[0]}><div className="photo"><img src={s[3]} alt="Industrial construction site"/><small>{s[0]}</small></div><div className="card-copy"><h3>{s[1]}</h3><p>{s[2]}</p><a href="#access">+</a></div></article>)}</div></section>
 <section className="section process" id="how"><div className="intro"><span className="label">02 / The process</span><h2>From request<br/>to <em>delivered.</em></h2></div><div className="steps">{steps.map(s=><div key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><Arrow/></div>)}</div></section>
 <section className="section intel" id="ai"><div className="visual"><img src="https://images.unsplash.com/photo-1517089596392-fb9a9033e05b?auto=format&fit=crop&w=1400&q=90" alt="Aerial view of a construction project"/><span>CV · ACTIVE</span><b>SITE CONDITION · 94%</b></div><div><span className="label">03 / Intelligence layer</span><h2>Built to notice<br/>what humans <em>miss.</em></h2><p className="lead">Practical AI, embedded into the work — not added as an afterthought.</p><div className="ai-list">{ai.map(a=><div key={a[0]}><span>{a[0]}</span><section><h3>{a[1]}</h3><p>{a[2]}</p></section></div>)}</div></div></section>
 <section className="emergency" id="emergency"><div><span className="kicker"><i/> 24/7 priority response</span><h2>Critical issue<br/>on site?</h2><p>The emergency portal assesses severity, alerts the right team, and records every step from report to resolution.</p><a className="btn dark" href="#access">Open emergency portal <Arrow/></a></div><div className="incident"><div className="ih"><span>NEW INCIDENT</span><b>00:42</b></div><small>LOCATION</small><strong>Site 3 · Lekki Free Zone</strong><small>INCIDENT TYPE</small><strong>Equipment failure</strong><small>SEVERITY ASSESSMENT</small><div className="bars"><i/><i/><i/><i/><i/></div><aside>◌ &nbsp; <span><b>Routing response team</b><br/>Nearest unit · 18 min ETA</span></aside></div></section>
 <section className="access" id="access"><span className="label">Start a conversation</span><h2>Build with<br/><em>certainty.</em></h2><p>Tell us what your sites need. We’ll show you how CED brings procurement, logistics, and support into one operating view.</p><a href="mailto:operations@ced.ng">operations@ced.ng <Arrow/></a></section>
 <footer><a className="brand" href="#top" aria-label="Back to top"><img src="/logo.png" alt=""/><span>CED <small>Integrated Nigeria Limited</small></span></a><p>Operational support for industrial supply chains across Nigeria.</p><div><a href="#services">Catalog</a><a href="#ai">Technology</a><a href="#emergency">Emergency</a></div><span>© 2026 CED Integrated Nigeria Limited</span></footer>
 </main>}
