"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function AuthPanel(){
 const [signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=new FormData(e.currentTarget),email=String(form.get("email")),password=String(form.get("password")),name=String(form.get("name")||""),organization=String(form.get("organization")||"");const sb=createClient();if(!sb){setMessage("Demo mode: add Supabase keys to .env.local to authenticate. Opening the product preview…");setTimeout(()=>location.href="/portal/dashboard",700);setBusy(false);return}const result=signup?await sb.auth.signUp({email,password,options:{data:{name,organization}}}):await sb.auth.signInWithPassword({email,password});if(result.error){setMessage(result.error.message);setBusy(false);return}if(signup&&!result.data.session){setMessage("Account created. Check your email to confirm your address, then sign in.");setBusy(false);return}location.href="/portal/dashboard"}
 return <main className="auth-page"><section className="auth-story"><Link className="brand" href="/"><b>C</b> CED</Link><div><span className="kicker"><i/> Operations, connected</span><h1>Command every site.<br/><em>From one place.</em></h1><p>Procurement, machinery, logistics and emergency support built for complex industrial work in Nigeria.</p></div><small>SECURE · AUDITABLE · MULTI-SITE</small></section><section className="auth-form"><div className="auth-box"><span className="label">CED workspace</span><h2>{signup?"Create your account":"Welcome back"}</h2><p>{signup?"Create an organization workspace and administrator profile.":"Sign in to your organization’s command centre."}</p><div className="auth-tabs"><button className={!signup?"active":""} onClick={()=>setSignup(false)}>Sign in</button><button className={signup?"active":""} onClick={()=>setSignup(true)}>Create account</button></div><form onSubmit={submit}>{signup&&<><label>Full name<input name="name" required placeholder="Amara Okafor"/></label><label>Organization<input name="organization" required placeholder="Meridian Developments"/></label></>}<label>Work email<input name="email" type="email" required placeholder="amara@company.ng"/></label><label>Password<input name="password" type="password" minLength={6} required placeholder="••••••••"/></label><button className="form-submit" disabled={busy}>{busy?"Please wait…":signup?"Create workspace account →":"Sign in →"}</button>{message&&<div className="form-message">{message}</div>}</form><small>By continuing, you agree to CED’s acceptable use and privacy policies.</small></div></section></main>
}
