/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

const nav=[['dashboard','⌂','Overview'],['catalog','⌘','Catalog'],['rfqs','↗','RFQs'],['bookings','▣','Machinery'],['remediation','◈','Remediation'],['orders','☷','Orders'],['emergency','!','Emergency'],['admin','⚙','Admin']];
const products=[
 {id:'1',category:'Equipment',name:'50T Rough Terrain Crane',location:'Lagos · Available',rate:'₦485,000 / day',img:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',tags:['AI matched','Operator']},
 {id:'2',category:'Aggregates',name:'Granite 20mm',location:'Lagos · 800 tonnes',rate:'Quote by volume',img:'https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?auto=format&fit=crop&w=800&q=80',tags:['Bulk','Fast dispatch']},
 {id:'3',category:'Equipment',name:'CAT 320 Excavator',location:'Ogun · Available',rate:'₦320,000 / day',img:'https://images.unsplash.com/photo-1579847188804-ecba0e2ea330?auto=format&fit=crop&w=800&q=80',tags:['Recommended','Tracked']},
 {id:'4',category:'Manpower',name:'Industrial Welding Crew',location:'Nationwide · 12 teams',rate:'From ₦95,000 / shift',img:'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',tags:['Verified','HSE certified']},
];
const demoOrders=[{reference:'ORD-2209',title:'Rebar 12mm · 42 tonnes',site:'Lekki Site 3',status:'Delivered',time:'Today, 09:42'},{reference:'BK-0311',title:'50T Rough Terrain Crane',site:'Ibadan Site 1',status:'In transit',time:'ETA 14:30'},{reference:'RFQ-1042',title:'Granite 20mm · 800 tonnes',site:'Lekki Site 3',status:'Reviewing',time:'Updated 18m ago'},{reference:'ENV-0087',title:'Hydrocarbon site survey',site:'Bonny Site 5',status:'Scheduled',time:'28 Sep, 08:00'}];
type Row=Record<string,unknown>;

export default function Portal({section}:{section:string}){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[orgId,setOrgId]=useState<string|null>(null),[menu,setMenu]=useState(false);
 const supabase=useMemo(()=>createClient(),[]);
 useEffect(()=>{let active=true;(async()=>{if(!supabase){setLoading(false);return}const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('profiles').select('org_id').eq('id',user.id).single();if(active)setOrgId(p?.org_id||null);const table:Record<string,string>={dashboard:'orders',catalog:'catalog_items',rfqs:'rfqs',bookings:'bookings',remediation:'remediation_requests',orders:'orders',emergency:'emergency_tickets',admin:'profiles'};const {data}=await supabase.from(table[section]).select('*').order('created_at',{ascending:false}).limit(30);if(active){setRows(data||[]);setLoading(false)}})();return()=>{active=false}},[section,supabase]);
 async function create(table:string,payload:Row){if(!supabase||!orgId){setToast('Saved in preview mode. Connect Supabase to persist this record.');return}const {error}=await supabase.from(table).insert({...payload,org_id:orgId});setToast(error?error.message:'Saved successfully');if(!error)location.reload()}
 async function logout(){if(supabase)await supabase.auth.signOut();location.href='/auth'}
 const title:Record<string,[string,string]>={dashboard:['Operations overview','All sites, orders and alerts in one operating view.'],catalog:['Industrial catalog','Equipment, materials and verified specialists ready for site.'],rfqs:['Requests for quote','Build bulk requests and compare transparent vendor offers.'],bookings:['Machinery & logistics','Reserve equipment and follow its route to site.'],remediation:['Environmental remediation','Document, assess and resolve ecological site conditions.'],orders:['Orders & shipments','A complete, auditable view of every active fulfilment.'],emergency:['Emergency response','Fast triage and direct escalation for critical site incidents.'],admin:['Platform administration','Manage catalog content, organizations and user access.']};
 return <div className="portal"><aside className={menu?'open':''}><div className="side-top"><Link className="brand" href="/"><b>C</b> CED</Link><button className="close-nav" onClick={()=>setMenu(false)}>×</button></div><div className="workspace"><small>WORKSPACE</small><strong>Meridian Developments</strong><span>Enterprise account</span></div><nav>{nav.map(n=><Link className={section===n[0]?'active':''} href={`/portal/${n[0]}`} key={n[0]}><i>{n[1]}</i>{n[2]}{n[0]==='emergency'&&<b/>}</Link>)}</nav><div className="side-user"><span>AO</span><div><strong>Amara Okafor</strong><small>Procurement lead</small></div><button onClick={logout}>↗</button></div></aside>
 <div className="portal-main"><header className="portal-head"><button className="menu-btn" onClick={()=>setMenu(true)}>☰</button><div className="crumb">CED / <b>{title[section][0]}</b></div><div className="head-tools"><button title="Search">⌕</button><button title="Notifications">♢<i/></button><span className="system"><i/> All systems normal</span></div></header><main className="portal-content"><div className="page-title"><div><span className="label">{section==='emergency'?'PRIORITY CHANNEL':'MERIDIAN DEVELOPMENTS'}</span><h1>{title[section][0]}</h1><p>{title[section][1]}</p></div>{section==='rfqs'&&<a href="#new-rfq" className="pbtn">+ New RFQ</a>}{section==='bookings'&&<a href="#booking" className="pbtn">+ Book equipment</a>}</div>
 {loading?<div className="loading">Loading secure workspace…</div>:<Screen section={section} rows={rows} search={search} setSearch={setSearch} create={create}/>}</main></div>{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}<b>×</b></div>}</div>
}

function Screen({section,rows,search,setSearch,create}:{section:string,rows:Row[],search:string,setSearch:(s:string)=>void,create:(t:string,p:Row)=>void}){
 if(section==='dashboard')return <Dashboard rows={rows}/>;
 if(section==='catalog')return <Catalog search={search} setSearch={setSearch}/>;
 if(section==='rfqs')return <Rfqs rows={rows} create={create}/>;
 if(section==='bookings')return <Bookings create={create}/>;
 if(section==='remediation')return <Remediation create={create}/>;
 if(section==='orders')return <Orders rows={rows}/>;
 if(section==='emergency')return <Emergency create={create}/>;
 return <Admin rows={rows}/>;
}

function Dashboard({rows}:{rows:Row[]}){const orders=rows.length?rows:demoOrders;return <><div className="stats"><article><span>ACTIVE ORDERS</span><strong>18</strong><small>↑ 3 this week</small></article><article><span>IN TRANSIT</span><strong>07</strong><small>Across 4 sites</small></article><article><span>OPEN RFQs</span><strong>05</strong><small>2 awaiting review</small></article><article className="alert-stat"><span>NEEDS ATTENTION</span><strong>02</strong><small>Action required</small></article></div><div className="dash-grid"><section className="panel activity"><PanelHead title="Active operations" link="/portal/orders"/><div className="table-head"><span>REFERENCE</span><span>ORDER / REQUEST</span><span>SITE</span><span>STATUS</span></div>{orders.slice(0,4).map((o:any)=><div className="op-row" key={String(o.reference||o.id)}><code>{String(o.reference||'ORDER')}</code><strong>{String(o.title||'Site order')}</strong><span>{String(o.site||'Active site')}</span><Status>{String(o.status||'Confirmed')}</Status></div>)}</section><section className="panel sites"><PanelHead title="Site health"/><div className="site-map"><div className="road r1"/><div className="road r2"/><Pin x="30%" y="28%" n="3"/><Pin x="68%" y="54%" n="1"/><Pin x="43%" y="76%" n="5"/></div><div className="site-legend"><span><i className="green-dot"/> 5 sites operational</span><span><i className="amber-dot"/> 1 delayed</span></div></section><section className="panel recommended"><PanelHead title="Picked for your sites" link="/portal/catalog"/><div className="rec-item"><img src={products[2].img} alt="Excavator"/><div><small>BASED ON RECENT ORDERS</small><strong>CAT 320 Excavator</strong><span>Available in Ogun · tracked</span></div><b>→</b></div></section><section className="panel timeline"><PanelHead title="Today"/><ul><li><i/>Crane BK-0311 departed depot <small>09:42</small></li><li><i/>Quote received from BuildCore <small>08:16</small></li><li><i/>Site 3 delivery confirmed <small>07:55</small></li></ul></section></div></>}
function PanelHead({title,link}:{title:string,link?:string}){return <div className="panel-head"><h2>{title}</h2>{link&&<Link href={link}>View all →</Link>}</div>}
function Status({children}:{children:React.ReactNode}){return <b className={`pill ${String(children).toLowerCase().replace(' ','-')}`}>{children}</b>}
function Pin({x,y,n}:{x:string,y:string,n:string}){return <span className="pin" style={{left:x,top:y}}>{n}</span>}

function Catalog({search,setSearch}:{search:string,setSearch:(s:string)=>void}){const [cat,setCat]=useState('All');const shown=products.filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(search.toLowerCase()));return <><div className="filters"><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search equipment, materials or manpower"/></div>{['All','Equipment','Aggregates','Manpower'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="catalog-grid">{shown.map(p=><article key={p.id}><div className="catalog-img"><img src={p.img} alt={p.name}/><button>♡</button></div><small>{p.category}</small><h2>{p.name}</h2><p>{p.location}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><footer><strong>{p.rate}</strong><Link href={p.category==='Equipment'?'/portal/bookings':'/portal/rfqs'}>Request →</Link></footer></article>)}</div></>}

function Rfqs({rows,create}:{rows:Row[],create:(t:string,p:Row)=>void}){const [step,setStep]=useState(1),[item,setItem]=useState('Granite 20mm'),[qty,setQty]=useState('800');function submit(e:FormEvent){e.preventDefault();create('rfqs',{status:'submitted',notes:`${qty} tonnes of ${item}`,needed_by:'2026-10-15'});setStep(4)}return <div className="rfq-layout"><section className="panel wizard" id="new-rfq"><div className="wizard-progress">{[1,2,3].map(n=><span className={step>=n?'done':''} key={n}>{n}<small>{['Items','Delivery','Review'][n-1]}</small></span>)}</div>{step<4?<form onSubmit={submit}><span className="label">STEP {step} OF 3</span><h2>{step===1?'What does your site need?':step===2?'Where and when?':'Review your request'}</h2>{step===1&&<div className="form-grid"><label>Item or material<select value={item} onChange={e=>setItem(e.target.value)}><option>Granite 20mm</option><option>Rebar 12mm</option><option>Industrial welding crew</option></select></label><label>Quantity<input value={qty} onChange={e=>setQty(e.target.value)}/></label><label>Unit<select><option>Tonnes</option><option>Units</option><option>Shifts</option></select></label><label>Specification<textarea placeholder="Add grade, dimensions, or other requirements"/></label></div>}{step===2&&<div className="form-grid"><label>Delivery site<select><option>Site 3 · Lekki Free Zone</option><option>Site 1 · Ibadan</option></select></label><label>Needed by<input type="date" defaultValue="2026-10-15"/></label><label>Delivery notes<textarea placeholder="Access instructions and receiving contact"/></label></div>}{step===3&&<div className="review-box"><span><small>REQUEST</small><b>{qty} tonnes · {item}</b></span><span><small>DELIVER TO</small><b>Site 3 · Lekki Free Zone</b></span><span><small>RESPONSE TARGET</small><b>First quote within 24 hours</b></span></div>}<div className="wizard-actions">{step>1&&<button type="button" onClick={()=>setStep(step-1)}>← Back</button>}<button className="pbtn" type={step===3?'submit':'button'} onClick={()=>step<3&&setStep(step+1)}>{step===3?'Submit RFQ':'Continue →'}</button></div></form>:<div className="success"><b>✓</b><h2>RFQ submitted</h2><p>Your request is now visible to approved vendors. We’ll notify you as quotes arrive.</p><button className="pbtn" onClick={()=>setStep(1)}>Create another</button></div>}</section><section className="panel quote-panel"><PanelHead title="Recent RFQs"/><div className="quote"><code>RFQ-1042</code><Status>Reviewing</Status><h3>Granite 20mm · 800 tonnes</h3><p>Site 3 · Lekki</p><div><span><small>QUOTES</small><b>3 received</b></span><span><small>BEST OFFER</small><b>₦18.4m</b></span></div><button>Compare quotes →</button></div>{rows.slice(0,2).map((r:any)=><div className="mini-row" key={String(r.id)}><code>{String(r.reference||'RFQ')}</code><span>{String(r.status)}</span></div>)}</section></div>}

function Bookings({create}:{create:(t:string,p:Row)=>void}){const [sent,setSent]=useState(false);return <div className="booking-grid"><section className="panel book-card" id="booking"><img src={products[0].img} alt="50 tonne crane"/><div><span className="label">SELECTED EQUIPMENT</span><h2>50T Rough Terrain Crane</h2><p>Certified operator · GPS tracking · Lagos depot</p><div className="availability"><i/> Available 29 Sep – 18 Oct</div><form onSubmit={e=>{e.preventDefault();create('bookings',{start_date:'2026-09-29',end_date:'2026-10-04',status:'confirmed',operator_required:true});setSent(true)}}><label>Site<select><option>Site 3 · Lekki Free Zone</option><option>Site 1 · Ibadan</option></select></label><div><label>Start date<input type="date" defaultValue="2026-09-29"/></label><label>End date<input type="date" defaultValue="2026-10-04"/></label></div><button className="pbtn">{sent?'Booking requested ✓':'Confirm booking · ₦2.91m'}</button></form></div></section><section className="panel tracking"><PanelHead title="Live logistics · BK-0311"/><div className="track-map"><span className="route-line"/><Pin x="22%" y="70%" n="A"/><Pin x="74%" y="22%" n="B"/><span className="truck" style={{left:'49%',top:'45%'}}>▰</span></div><div className="eta"><span><small>CURRENT LOCATION</small><strong>Lagos–Ibadan Expressway</strong></span><span><small>ETA TO SITE</small><strong>1h 42m</strong></span></div><div className="track-steps"><span className="done"><i/>Dispatched<small>08:10</small></span><span className="done"><i/>In transit<small>09:42</small></span><span><i/>Site arrival<small>ETA 14:30</small></span></div></section></div>}

function Remediation({create}:{create:(t:string,p:Row)=>void}){const [files,setFiles]=useState(0),[result,setResult]=useState(false);return <div className="rem-grid"><form className="panel rem-form" onSubmit={e=>{e.preventDefault();create('remediation_requests',{description:'Suspected hydrocarbon contamination near storage area',incident_type:'Hydrocarbon contamination',status:'submitted',cv_assessment:{risk:'medium',vegetation_stress:true}});setResult(true)}}><span className="label">NEW ASSESSMENT</span><h2>Describe the site condition</h2><div className="form-grid"><label>Site<select><option>Site 5 · Bonny Industrial Area</option></select></label><label>Incident type<select><option>Hydrocarbon contamination</option><option>Erosion / land degradation</option><option>Waste management</option><option>Water contamination</option></select></label><label>Details<textarea required defaultValue="Suspected hydrocarbon contamination near storage area. Vegetation discoloration visible."/></label><label className="upload">Site photos<input type="file" multiple accept="image/*" onChange={e=>setFiles(e.target.files?.length||0)}/><span>＋ Drop photos or browse<br/><small>{files?`${files} photo(s) ready for assessment`:'JPG, PNG up to 10MB each'}</small></span></label></div><button className="pbtn">Submit for assessment →</button></form><section className="panel vision"><div className="vision-img"><img src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80" alt="Environmental site"/><span>AI VISION ANALYSIS</span><i/><i/><i/></div><div className="vision-copy"><h2>{result?'Assessment ready':'Computer vision preview'}</h2><p>{result?'Potential surface contamination identified. Human review has been requested.':'Upload site photographs to detect vegetation stress, surface contamination, erosion and equipment damage.'}</p><div><span><small>CONFIDENCE</small><b>{result?'91%':'—'}</b></span><span><small>PRIORITY</small><b>{result?'MEDIUM':'PENDING'}</b></span></div></div></section></div>}

function Orders({rows}:{rows:Row[]}){const [view,setView]=useState('board'),list=rows.length?rows:demoOrders;return <><div className="order-tools"><div><button className={view==='board'?'active':''} onClick={()=>setView('board')}>Board</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>List</button></div><button>↻ Refresh status</button></div>{view==='board'?<div className="kanban">{['Confirmed','In transit','Delivered'].map((status,i)=><section key={status}><header><span>{status}</span><b>{i===0?2:i===1?1:1}</b></header>{(i===0?demoOrders.slice(2):i===1?demoOrders.slice(1,2):demoOrders.slice(0,1)).map(o=><article key={o.reference}><code>{o.reference}</code><h3>{o.title}</h3><p>{o.site}</p><footer><Status>{o.status}</Status><span>{o.time}</span></footer></article>)}</section>)}</div>:<section className="panel activity">{list.map((o:any)=><div className="op-row" key={String(o.reference||o.id)}><code>{String(o.reference||'ORDER')}</code><strong>{String(o.title||'Site order')}</strong><span>{String(o.site||'Active site')}</span><Status>{String(o.status||'Confirmed')}</Status></div>)}</section>}</>}

function Emergency({create}:{create:(t:string,p:Row)=>void}){const [message,setMessage]=useState(''),[triage,setTriage]=useState<any>(null),[busy,setBusy]=useState(false);async function send(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message})}),data=await r.json();setTriage(data);create('emergency_tickets',{severity:data.severity,description:message,ai_triage:data,status:'open'});setBusy(false)}return <div className="emergency-grid"><section className="emergency-call"><span className="kicker"><i/> Emergency operations channel</span><h2>Report a critical<br/>site issue.</h2><p>For immediate threats to life, call local emergency services first. CED coordinates operational response, equipment and site support.</p><div className="hotline"><small>PRIORITY HOTLINE</small><a href="tel:+2347000000233">+234 700 0000 CED</a></div></section><section className="panel triage"><div className="chat-head"><span>AI TRIAGE ASSISTANT</span><i>ONLINE</i></div><div className="chat-body"><div className="bot">Tell me what happened, where it happened, and whether anyone is in immediate danger.</div>{triage&&<><div className="person">{message}</div><div className="bot"><b>{String(triage.severity).toUpperCase()} PRIORITY</b><br/>{triage.summary}<div className="triage-result"><span>ROUTED TO</span><strong>{triage.route}</strong><span>ESTIMATED RESPONSE</span><strong>{triage.eta} minutes</strong></div></div></>}</div><form onSubmit={send}><textarea required value={message} onChange={e=>setMessage(e.target.value)} placeholder="Describe the incident…"/><button disabled={busy}>{busy?'Assessing…':'Send report →'}</button></form></section></div>}

function Admin({rows}:{rows:Row[]}){const [tab,setTab]=useState('Catalog');return <><div className="admin-tabs">{['Catalog','Organizations','Users','Content'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><section className="panel admin-panel"><div className="admin-head"><div><h2>{tab} management</h2><p>Changes are written to the shared workspace and recorded in the audit log.</p></div><button className="pbtn">+ Add {tab.slice(0,-1)}</button></div><div className="admin-table"><div><b>NAME</b><b>TYPE / ROLE</b><b>STATUS</b><b>LAST UPDATED</b><b/></div>{(tab==='Catalog'?products:tab==='Users'?[{name:'Amara Okafor',category:'Procurement lead'},{name:'Tunde Adebayo',category:'Site engineer'},{name:'Chidi Nwosu',category:'Org admin'}]:[{name:'Meridian Developments',category:'Enterprise'},{name:'Apex Civil Works',category:'Construction'},{name:'Rivers Infrastructure Agency',category:'Government'}]).map((x:any,i)=><div key={x.name}><strong>{x.name}</strong><span>{x.category}</span><Status>{i===2?'Pending':'Active'}</Status><span>{i+2} days ago</span><button>•••</button></div>)}</div><div className="audit"><span className="label">LATEST AUDIT EVENT</span><p><b>Amara Okafor</b> updated catalog availability · Today, 10:14 · IP logged</p></div>{rows.length>0&&<small>{rows.length} live database records loaded.</small>}</section></>}
