create extension if not exists "pgcrypto";

create type public.user_role as enum ('org_admin','procurement','site_engineer','platform_admin');
create type public.workflow_status as enum ('draft','submitted','reviewing','quoted','confirmed','scheduled','in_transit','delivered','cancelled','open','resolved');

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, type text, region text, cac_number text, created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users on delete cascade, org_id uuid references public.organizations on delete cascade, role public.user_role not null default 'procurement', name text not null, phone text, email text, created_at timestamptz default now());
create table public.sites (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations on delete cascade, name text not null, location text, latitude double precision, longitude double precision, created_at timestamptz default now());
create table public.catalog_items (id uuid primary key default gen_random_uuid(), category text not null check(category in ('equipment','aggregates','manpower','remediation')), name text not null, description text, image_url text, tags text[] default '{}', daily_rate numeric, available boolean default true, created_at timestamptz default now());
create table public.rfqs (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations, site_id uuid references public.sites, status public.workflow_status default 'draft', created_by uuid references public.profiles, reference text unique default ('RFQ-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))), needed_by date, notes text, created_at timestamptz default now());
create table public.rfq_items (id uuid primary key default gen_random_uuid(), rfq_id uuid references public.rfqs on delete cascade, catalog_item_id uuid references public.catalog_items, item_name text, qty numeric not null, unit text default 'unit', notes text);
create table public.quotes (id uuid primary key default gen_random_uuid(), rfq_id uuid references public.rfqs on delete cascade, vendor_name text not null, price numeric not null, valid_until date, lead_days int, status text default 'received', created_at timestamptz default now());
create table public.bookings (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations, site_id uuid references public.sites, catalog_item_id uuid references public.catalog_items, start_date date not null, end_date date not null, status public.workflow_status default 'confirmed', operator_required boolean default true, created_at timestamptz default now());
create table public.logistics_events (id uuid primary key default gen_random_uuid(), booking_id uuid references public.bookings on delete cascade, status public.workflow_status not null, location text, latitude double precision, longitude double precision, note text, created_at timestamptz default now());
create table public.remediation_requests (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations, site_id uuid references public.sites, description text not null, incident_type text, photos text[] default '{}', cv_assessment jsonb default '{}', status public.workflow_status default 'submitted', created_at timestamptz default now());
create table public.orders (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations, site_id uuid references public.sites, source_type text, source_id uuid, reference text unique default ('ORD-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))), title text not null, status public.workflow_status default 'confirmed', total numeric default 0, created_at timestamptz default now());
create table public.order_status_updates (id uuid primary key default gen_random_uuid(), order_id uuid references public.orders on delete cascade, status public.workflow_status not null, note text, actor uuid references public.profiles, created_at timestamptz default now());
create table public.emergency_tickets (id uuid primary key default gen_random_uuid(), org_id uuid not null references public.organizations, site_id uuid references public.sites, severity text not null check(severity in ('low','medium','high','critical')), description text not null, ai_triage jsonb default '{}', status public.workflow_status default 'open', created_at timestamptz default now());

alter table public.organizations enable row level security; alter table public.profiles enable row level security; alter table public.sites enable row level security; alter table public.catalog_items enable row level security; alter table public.rfqs enable row level security; alter table public.rfq_items enable row level security; alter table public.quotes enable row level security; alter table public.bookings enable row level security; alter table public.logistics_events enable row level security; alter table public.remediation_requests enable row level security; alter table public.orders enable row level security; alter table public.order_status_updates enable row level security; alter table public.emergency_tickets enable row level security;

create function public.current_org_id() returns uuid language sql stable security definer set search_path=public as $$ select org_id from public.profiles where id=auth.uid() $$;
create policy "catalog readable authenticated" on public.catalog_items for select to authenticated using (true);
create policy "profiles same org" on public.profiles for select to authenticated using (org_id=public.current_org_id());
create policy "organizations own" on public.organizations for select to authenticated using (id=public.current_org_id());
create policy "sites org isolation" on public.sites for all to authenticated using (org_id=public.current_org_id()) with check (org_id=public.current_org_id());
create policy "rfqs org isolation" on public.rfqs for all to authenticated using (org_id=public.current_org_id()) with check (org_id=public.current_org_id());
create policy "rfq items via parent" on public.rfq_items for all to authenticated using (exists(select 1 from public.rfqs r where r.id=rfq_id and r.org_id=public.current_org_id())) with check (exists(select 1 from public.rfqs r where r.id=rfq_id and r.org_id=public.current_org_id()));
create policy "quotes via parent" on public.quotes for select to authenticated using (exists(select 1 from public.rfqs r where r.id=rfq_id and r.org_id=public.current_org_id()));
create policy "bookings org isolation" on public.bookings for all to authenticated using (org_id=public.current_org_id()) with check (org_id=public.current_org_id());
create policy "logistics via booking" on public.logistics_events for select to authenticated using (exists(select 1 from public.bookings b where b.id=booking_id and b.org_id=public.current_org_id()));
create policy "remediation org isolation" on public.remediation_requests for all to authenticated using (org_id=public.current_org_id()) with check (org_id=public.current_org_id());
create policy "orders org isolation" on public.orders for all to authenticated using (org_id=public.current_org_id()) with check (org_id=public.current_org_id());
create policy "order updates via order" on public.order_status_updates for select to authenticated using (exists(select 1 from public.orders o where o.id=order_id and o.org_id=public.current_org_id()));
create policy "tickets org isolation" on public.emergency_tickets for all to authenticated using (org_id=public.current_org_id()) with check (org_id=public.current_org_id());

insert into storage.buckets (id,name,public) values ('catalog','catalog',true),('inspections','inspections',false) on conflict do nothing;
create policy "authenticated inspection upload" on storage.objects for insert to authenticated with check (bucket_id='inspections' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "own inspection read" on storage.objects for select to authenticated using (bucket_id='inspections' and (storage.foldername(name))[1]=auth.uid()::text);

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare new_org uuid; begin insert into public.organizations(name,type) values(coalesce(new.raw_user_meta_data->>'organization','New organization'),'Enterprise') returning id into new_org; insert into public.profiles(id,org_id,role,name,email) values(new.id,new_org,'org_admin',coalesce(new.raw_user_meta_data->>'name','CED User'),new.email); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
